[package]
name = "pcf"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
hex_color = "3.0.0"
image = "0.25.5"
postcard = "1.1.1"
rust-lzma = "0.6.0"
serde = { version = "1.0.217", features = ["derive"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = 'abort'
debug = false
rpath = false
strip = true
debug-assertions = false

[profile.release.package."*"]
opt-level = 3
debug = false
codegen-units = 1
incremental = false
strip = true
